#!/bin/bash

export OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION:-2.0}
export OS_USERNAME=${OS_USERNAME:-admin}
export OS_PASSWORD=${OS_PASSWORD:-secretsecret}
export OS_AUTH_URL=${OS_AUTH_URL:-http://192.168.123.100:5000/v2.0}
export OS_TENANT_NAME=${OS_TENANT_NAME:-admin}
export OS_TENANT_ID=${OS_TENANT_ID:-c7ea5d39a6754852b5baaf32a737a180}
export OS_REGION_NAME=${OS_REGION_NAME:-RegionOne}
